#ifndef __PORT_H__
#define __PORT_H__

#include "Main.h"

/* Leds' pins */
#define UP_BTN_PORT_DR   (GPIO_PORT0_DATA)
#define UP_BTN_PORT_CR   (GPIO_PORT0_DIRECTION)
#define UP_BTN_PIN       (GPIO_PIN_0)

#define DOWN_BTN_PORT_DR   (GPIO_PORT0_DATA)
#define DOWN_BTN_PORT_CR   (GPIO_PORT0_DIRECTION)
#define DOWN_BTN_PIN       (GPIO_PIN_1)

#define F0_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define F0_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define F0_BTN_PIN       (GPIO_PIN_2)

#define F1_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define F1_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define F1_BTN_PIN       (GPIO_PIN_3)

#define F2_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define F2_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define F2_BTN_PIN       (GPIO_PIN_4)

#define F3_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define F3_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define F3_BTN_PIN       (GPIO_PIN_5)

#define F4_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define F4_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define F4_BTN_PIN       (GPIO_PIN_6)

#define FORCE_OPEN_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define FORCE_OPEN_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define FORCE_OPEN_BTN_PIN       (GPIO_PIN_7)

#define SEVEN_SEGMENT_DR   (GPIO_PORT1_DATA)
#define SEVEN_SEGMENT_CR   (GPIO_PORT1_DIRECTION)

#define INCREASE_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define INCREASE_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define INCREASE_BTN_PIN       (GPIO_PIN_0)


#define DECREASE_BTN_PORT_DR   (GPIO_PORT2_DATA)
#define DECREASE_BTN_PORT_CR   (GPIO_PORT2_DIRECTION)
#define DECREASE_BTN_PIN       (GPIO_PIN_1)

#define MOVING_LED_PORT_DR   (GPIO_PORT3_DATA)
#define MOVING_LED_PORT_CR   (GPIO_PORT3_DIRECTION)
#define MOVING_LED_PIN       (GPIO_PIN_0)

#define DOOR_OPEN_LED_PORT_DR   (GPIO_PORT3_DATA)
#define DOOR_OPEN_LED_PORT_CR   (GPIO_PORT3_DIRECTION)
#define DOOR_OPEN_LED_PIN       (GPIO_PIN_1)

#define ALARM_LED_PORT_DR   (GPIO_PORT3_DATA)
#define ALARM_LED_PORT_CR   (GPIO_PORT3_DIRECTION)
#define ALARM_LED_PIN       (GPIO_PIN_2)

/* End of code filling */
#endif // __PORT_H__
